### ISSUE TITLE
Support  Installable Triggers 

### ISSUE THREAD

**Issue by azu** [uknmr/gas-webpagetest#16]
[Installable Triggers  |  Apps Script  |  Google Developers](https://developers.google.com/apps-script/guides/triggers/installable)でTime Triggerをスクリプト側で指定できそうな気がします。

`.env`にCRON的な設定を書かせて、deployするだけtime triggerの設定ができるようになると便利そうな気がします。(設定がコードとして管理できる)
今、細かい手順のREADMEを書いてみてるのですが、Trigger部分だけGUIの説明になってしまうので、これを避けたいという意図もあります。

## TODO

- Triggerの同一性の保証をする方法があるのかなどうか
  - `triggerId` というUnique IDがあるけど、これを指定できるのか
  - アップデートするためにTriggerが重複して増えるのを防止しないといけない
- `onOpen` のときに設定すれば、Triggerを自動的に追加できそうだけど、動くか未検証。

**Comment by uknmr** [comment]
おおおー Time Trigger の設定できるんですね

**Comment by uknmr** [comment]
`onOpen` に混ぜ込んでみたけど追加されませんでした。

```js
function onOpen() {
  // 略
  ScriptApp.newTrigger('runTest')
    .timeBased()
    .everyMinutes(30)
    .create()

  ScriptApp.newTrigger('getTestResults')
    .timeBased()
    .everyHours(2)
    .create()
}
```
