### ISSUE TITLE
Add step by step guide

### ISSUE THREAD

**Issue by azu** [uknmr/gas-webpagetest#17]
今のREADMEはおそらく既にWebPageTestとSpreadSheetとGoogle Apps Scriptを使ったことがある人じゃないと、導入が難しいと思います。

- https://github.com/uknmr/gas-webpagetest
- 類似ツール: [andydavies/WPT-Bulk-Tester: Google App Script for spreadsheet that uses the WPT API to bulk test URLs](https://github.com/andydavies/WPT-Bulk-Tester)

どこまで設定を簡略するかは検討が必要そうですが、ステップバイステップのREADMEがあると良さそうな気がします。(clasp周りとdeploy周りがあるので、完全な自動化をめざすよりは詳細をはっきりしていくのがいいかなと思います。)

後、日本語に依存するツールじゃないのでREADMEは英語でも用意した方が良さそうな気がします。

https://github.com/uknmr/gas-webpagetest/issues/17#issuecomment-409173099 にとりあえずの仮ステップバイステップを書いてみました。

**Comment by azu** [comment]
## Requirements

- Node.js
  - This script is written by Node.js
- Yarn
  - pacakge manager
  - This repository is manged by Yarn
- Google Account
  - Need to login with [clasp](https://github.com/google/clasp).
  - `gas-webpagtest` is a Google Apps Script.
- Google SpreadSheet
  - `gas-webpagtest` record the result of WebPageTest to Google Spreadsheet
  - 1 sheet = 1 site
- WebPageTest API Key
  - [WebPagetest - Get API Key](https://www.webpagetest.org/getkey.php)
  - `gas-webpagtest` call WebPagetest API and record it.

### Optional

- Google DataStudio
  - It help visualization of data

## Usage

### Installation

1. git clone this repository

```
git clone https://github.com/uknmr/gas-webpagetest.git
cd gas-webpagetest
```

2. Install dependencies by yarn


```
yarn install
```


3. If you never use `clasp`, please do `clasp login`

```
yarn clasp login
# Login and Authrize clasp
```

### Integrate Google Spreadsheet with Google Apps Script(gas-webpagtest)

4. Create empty spreadsheet that is recored result of WebPagetest.
  - You should copy spreadsheet id
  - For example, your spreadsheet url is `https://docs.google.com/spreadsheets/d/asn__asxScJZi-2asd4242sd23HO441Ok/edit#gid=0`
  - `asn__asxScJZi-2asd4242sdHOeB6t5XFdOk` is a **spreadsheet id** and copy it
5. Create new Google Apps Script and connect it the spreadsheet.
  - If success it, `.clasp.json` is created.
  - First argument is Google Apps Script title
  - Second argument is **spreadsheet id**

```
yarn clasp create "gas-webpagetest" "<spreadsheet id>"
# Example
# yarn clasp create "gas-webpagetest-example" "asn__asxScJZi-2asd4242sdHOeB6t5XFdOk"
```

:memo: If you met foollowing error, you have to visit the url and enable the Apps Script API.

> Error: Permission denied. Enable the Apps Script API:
> https://script.google.com/home/usersettings

6. Modify `.clasp.json`
  - Add `rootDir` to `.clasp.json`
  
Changet the `.clasp.json`

```json
{"scriptId":"x1233-2asd4x2444442sdHOeB6sdkdfkjsdljsdlkfjdsklfjt5XFdOk"}
```

to

```json
{"scriptId":"x1233-2asd4x2444442sdHOeB6sdkdfkjsdljsdlkfjdsklfjt5XFdOk", "rootDir": "dist"}
```

7. Copy `.env.example` to `.env` and setting it.

You can get `WEBPAGETEST_API_KEY` from [WebPagetest - Get API Key](https://www.webpagetest.org/getkey.php).

```.env
WEBPAGETEST_API_KEY=<webpagetest_api_key>
RUN_TEST_URL=https://example.com/
SHEET_NAME=<Spreadsheet's sheet name>

# ==CUSTOMIZE WEBPAGEST OPTIONS==
# WebPagetest Options
# https://sites.google.com/a/webpagetest.org/docs/advanced-features/webpagetest-restful-apis
## Number of test runs (1-10 on the public instance)
## gas-webpagetest use median results
WEBPAGETEST_OPTIONS_RUNS=3
# ... Other .... 
```


8. Deploy the gas-webpagetest script to your Google Apps Script: `yarn run deploy`

Run following command that deploy this script.

```
yarn run deploy
```

## Setting schedule for `gas-webpagtest`

`gas-webpagtest` provide these function.

- Run Test
  - Run test that call WebPagetest API
- Get Test results
  - Get results of the test and write it to spreadsheet
- Update column titles
  - Update spreadsheet title columns

These functions can be called by manually.
However, These functions can be called regularly by **Time Trigger**.

- [Simple Triggers  |  Apps Script  |  Google Developers](https://developers.google.com/apps-script/guides/triggers/)

You can set time trigger like cron for `gas-webpagtest`

Example

- Run Test per 1 hour
- Get Test results per 10 minutes

## Optional: Visualize

[Google DataStudio](https://datastudio.google.com) help to visualize your spreadsheet data.

- TODO: Copy template for `gas-webpagtest` from HERE

**Comment by uknmr** [comment]
ありがとうございます！
WebPagetest と Spreadsheet の表記ゆれ編集と typo 修正しました🙏

Time Trigger の TODO に貼るリンクはこっちですかね？
-  [Installable Triggers  |  Apps Script  |  Google Developers](https://developers.google.com/apps-script/guides/triggers/installable)

**Comment by uknmr** [comment]
ほぼ上の記述のまま README 更新しようと思います🙏

**Comment by azu** [comment]
手元で4-7をまとめてやるスクリプトを書いてたので、後で手直してしてPRを出します。
あとclasp 1.5系のバグが治ったらしいので、その辺も修正かな。

> Setting schedule for gas-webpagtest

あたりは #18 で追加しやつに変えられそうかな(メニューからスケジュール登録できるよ的な)

**Comment by uknmr** [comment]
ありがとうございます。

#18 のやつは `Set run test time triggers` で登録できるよ、って説明にとどめています。
こんな感じ。

```markdown
## Setting schedule for `gas-webpagtest`

`gas-webpagtest` provide these functions.

- Run Test
  - Run test that call WebPagetest API
- Get Test results
  - Get results of the test and write it to spreadsheet
- Update column titles
  - Update spreadsheet title columns

These functions can be called manually.
However, These functions can be regularly called by **Time Trigger**.

So, you can set **Time Trigger** by the following function.

- Set run test time triggers
  - You can set time trigger like cron
  - By default, it is per 30 minutes
```
