### ISSUE TITLE
All options should be in .env

### ISSUE THREAD

**Issue by azu** [uknmr/gas-webpagetest#3]
`generateRunTestURL`のオプションを指定する方法がないため、
`.env` から指定できるようにしたい。

現状だとソースコードを変更しないと、PCで計測が行えないなどの問題があるため、

## Proposal

- オプションに対応する項目を `.env` に追加する
  - 他のenvと混ざるのを避けるため `WEBPAGETEST_OPTIONS_` prefixをつける
- デフォルト値は現状維持

例)

```
WEBPAGETEST_API_KEY=key
RUN_TEST_URL=http://example.com
SHEET_NAME=stats
WEBPAGETEST_OPTIONS_RUNS=3
WEBPAGETEST_OPTIONS_MOBILE=0
````

**Comment by uknmr** [comment]
いいと思います！
オプション項目の追加予定はありますか？
（現状自分がつかうものしか書いていないので…）

**Comment by azu** [comment]
いまのところ他に欲しいのは `script` #4 ぐらいなので、他は特に追加予定がないですね。
他のオプションは必要になったら追加とかでもいい気はします。

https://sites.google.com/a/webpagetest.org/docs/advanced-features/webpagetest-restful-apis
