### ISSUE TITLE
:question: スプレッドシートからテスト結果が消える

### ISSUE THREAD

**Issue by aar1nana7** [uknmr/gas-webpagetest#32]
## 症状
- テスト結果がスプレッドシートに記録されなくなった
- テスト後一旦は結果が反映されるがしばらくするとID以外は消えてしまう

![spredsheet](https://i.gyazo.com/a3271cc8d281aee48b8994bb11a7faff.png)

## スクリプトのログ
```
[19-07-04 18:37:25:764 PDT] lastTestIdRow: 1821.0, lastCompletedRow: 1692.0
[19-07-04 18:37:25:876 PDT] testIds: 190702_Z0_74b55bd334fd4a94b134d9980d22d351
190702_K2_132f2516149cdad725c3c681c3b63b97
190702_XN_26db6fead13901e337eb8f66bb8fc1da
190702_7S_62c71c6b31ee2198a907739a3570dc85
190702_99_b9233fe2a3aa43db967ef1332fcd3a84
190702_4F_21f1637879a38d3dfd9fb40bcd935f05
190702_DX_45f1e113e700d9f41e36240a7dcc0885
190702_EA_d2ada738f33741ad20c20579c686b9e8
190702_6V_b92c3584a246a5658de31ef3de81ba7d
190702_H9_df7925d3a7b954e8c271d974a8b1a5a5
190702_5F_64468081df1a80b4f3b67bc177223007
190702_TQ_bc8370559a3850e5efdce7874be3d96d
190702_FV_19f3c79cbdc9b9002f2827d33aa15ee5
190702_FC_4e4e06b62110384f189ddf142736de8f
190702_3Q_4b7196cd0319863bd5c0d1786262cfd0
・
・
・
以下IDの羅列が続く
```

## Developer Hubの実行履歴
- スプレッドシートに残っている最後の記録は 7/2 17:00
- Developer Hubで 7/2 15:00 に onOpen といういつもとは違う実行履歴が残っている 

![AppsScript](https://i.gyazo.com/cc13527e3cb7c789a44d9d81844fd7c1.png)

**Comment by uknmr** [comment]
私の手元の環境でも `onOpen` という関数がなぜか「トリガー」で実行されているのを確認しました。
しかし私の方ではデータが消えていませんでした。

`onOpen` 関数はスプレッドシートに「gas-webpagetest」という名前のメニューを追加する関数なので記録への影響はありません。
念の為、実行してみましたが影響はありませんでした。

消えてしまっている原因はわかりませんが理由は別にありそうです。
gas-webpagetest が持っている関数の中にデータを消すものは存在していません。

またデータが歯抜けになるということはありえません。

testId | completedTimeStamp | ...
--- | --- | ---
hoge | 1545292565 | ...
fuga | |
puyo |  | 

とあった場合には fuga と puyo のデータを取りに行きます。

testId | completedTimeStamp | ...
--- | --- | ---
hoge | | 
fuga | 1545294895 | ...
puyo |  | 

添付画像のような場合には puyo のみ取りに行きます。この場合の hoge は次の行の fuga にデータが入っているため「取得済み」扱いになります。

WebPagetest 側にデータが残っていれば（仕様ではテストが実行されてから 30 日間）、再度データを取ってくることができます。
下記の手順でリカバリできるかもしれません。

1. トリガーをすべて削除
1. 万が一のためにシートをコピー
1. 取得できているデータを削除
1. スプレッドシートの gas-webpagetest メニューから「Get test results」を実行
    - 件数が多ければ多いほど時間がかかります
    - 分けて実行してもいいかもしれません
1. データが入力されたら gas-webpagetest メニューから「Set run test time triggers」を実行
    - 以前の実行時間とズレは出ますがご了承ください

**Comment by aar1nana7** [comment]
教えていただいたリカバリ方法を試してみましたが、直近の3件のみテスト結果取得でき、残りの100件近くは取得できずでした。
取得できていないテスト結果のURLを直接叩いてみたところWebPagetest側にデータは残っているにもかかわらずです。

この場合データ丸ごと削除して新しく作り直すほかないでしょうか？

**Comment by aar1nana7** [comment]
コメント後に発現しましたが、時間の経過により先ほど取得できた直近の3件ともtestIDを残して結果が消えていました。。

**Comment by uknmr** [comment]
直近 3 件しか取得できなかったのと、それすらも消えてしまうのはとても不思議ですね🤔
お手数ですが問題の切り分けのため再度最初からつくり直していただくことは可能でしょうか？

私の方でも時間を見つけて確認してみます🙏

**Comment by aar1nana7** [comment]
参考になるか分かりませんが、下記の管理状況だったことを共有しておきます。
・Aサイト,Bサイト,Cサイトと3サイト分管理している
・各サイト用にgoogleアカウントを作成しAPIKeyを取得
・スプレッドシートはAサイト用のアカウント内で全て作成

作り直す場合はスプレッドシートも各アカウントに持たせるように作成してみます。

**Comment by aar1nana7** [comment]
3サイト分すべてそれぞれのアカウント上で作り直し、現状すべて正常にデータを取得できています。

新規で作成したものにtestIDを貼り付け（APIkeyは変更せずに運用）Get test resultsで取得できるかと思ってましたが叶わずでした。。

**Comment by uknmr** [comment]
> 現状すべて正常にデータを取得できています

良かったです！

gas-webpagetest の仕様では `completedTimeStamp` が入力されている行より前は取得しません。
WebPagetest の方はテスト実行から 30 日間は再度データが取得できたと思います。
件数が多い場合はかなり時間がかかるので余裕を見て実行するか、小分けに実行するといいかもしれません😇
