### ISSUE TITLE
Support WebPagetest scripting 

### ISSUE THREAD

**Issue by azu** [uknmr/gas-webpagetest#4]
WebPagetestのscriptingをサポートしたいです。
特定の処理をしてから計測ページに行く場合やログインが必要なサイトの計測などに利用できます。

- [Scripting - WebPagetest Documentation](https://sites.google.com/a/webpagetest.org/docs/using-webpagetest/scripting)

## Proposal

- `.env` に複数行を書けないため、`script.txt`のようなファイル指定でサポートする
  - <https://github.com/motdotla/dotenv/issues/196>
- `script.txt`があるならリクエストに`?script=<SCRIPT>`を追加する
- `script.txt`がないならリクエストに`?script`を追加しない
- `.gitignore`で`script.txt`を無視する(Git管理下にはおかない)
  - `.env` と同じような扱い

## 実装方法

webpack.config.js で env のreplaceに特別な処理を入れる。
これで、コード中の `process.env.WEBPAGETEST_OPTIONS_SCRIPT` が `script.txt` の中身と入れ替えることができる。(envである必要はないけど)

`script.txt` がない場合はただの空文字になる。

```js
const path = require('path')
const Dotenv = require('dotenv-webpack')
const GasPlugin = require('gas-webpack-plugin')
const webpack = require('webpack')
const fs = require("fs");
const WEBPAGETEST_OPTIONS_SCRIPT = fs.existsSync("script.txt") ? fs.readFileSync("script.txt", "uft-8") : "";
module.exports = {
    mode: 'none',
    entry: {
        runTest: './src/runTest.ts',
        getTestResults: './src/getTestResults.ts',
    },
    output: {
        path: path.resolve(__dirname, 'dist'),
        filename: '[name].js',
    },
    module: {
        rules: [
            {
                test: /\.ts$/,
                use: 'ts-loader',
            },
        ],
    },
    resolve: {
        extensions: ['.ts', '.js'],
    },
    devtool: false,
    plugins: [
        new Dotenv(),
        new webpack.DefinePlugin({
            "process.env.WEBPAGETEST_OPTIONS_SCRIPT": JSON.stringify(WEBPAGETEST_OPTIONS_SCRIPT)
        }),
        new GasPlugin()
    ],
}
```

**Comment by uknmr** [comment]
わかりやすく書いていただいてありがとうございます。
問題ないです！
