### ISSUE TITLE
Add missing record

### ISSUE THREAD

**Issue by azu** [uknmr/gas-webpagetest#5]
WebPageTestの結果は1ヶ月で取れなくなるので、記録できるものはできるだけ記録しておきたいです。

次の項目が抜けているような気がします。

- URL: `data.median.firstView.final_url`
  - 実際に計測したURL。scriptingをした時やリダイレクトされている時などはtestURLとは違う場合がある。
- browserName	`data.median.firstView.browser_name`
- browserVersion	`data.median.firstView.browserVersion`
  - バージョンで結果が変わる可能性がある
- visualComplete85	`data.median.firstView.visualComplete85`
- visualComplete90	`data.median.firstView.visualComplete90`
- visualComplete95	`data.median.firstView.visualComplete95`
- visualComplete99	`data.median.firstView.visualComplete99`
  - speed indexで大体カバーされますが一応
- breakdown.flash.bytes	`data.median.firstView.breakdown.flash.bytes`
- breakdown.flash.requests	`data.median.firstView.breakdown.flash.requests`
- breakdown.video.bytes	`data.median.firstView.breakdown.video.bytes`
- breakdown.video.requests	`data.median.firstView.breakdown.video.requests`
  - breakdownで抜けている部分

他には通信系があります(説明は[Using WebPageTest](http://shop.oreilly.com/product/0636920033592.do)より)

- bytesOut: The total bytes sent from the browser to other servers.
- bytesOutDoc: Same as bytesOut but only includes bytes until the Document Completeevent. Usually when all the page content has loaded (window.onload).
- bytesIn: The amount of data that browser had to download in order to load the page. Itis also commonly referred to as the page size.
- bytesInDoc: Same as bytestIn but only includes bytes until Document Completeevent.
- connections: The number of connections used.requests: List of details of all requests on tested page.
- requestsDoc: The number of requests until Document Complete event.
- responses_200: The number of responses with HTTP status code of 200, OK.
- responses_404: The number of responses with HTTP status code of 404, not　found.
- responses_other: The number of responses with HTTPS status code different from 200 or 404

他にはブラウザ固有のデータもありますが、歯抜けになるので含める必要はないかもしれません。
(現在も `firstLayout` がChromeのみなので混ざってはいそうです。既存の値とかぶっていそう)

Firefoxのみ

- `data.median.firstView.FirstInteractive` 
- `data.median.firstView.TTIMeasurementEnd`

Chromeのみ

- `data.median.firstView["chromeUserTiming.*"]`

## 追加するもの

実際に追加したいもの。

- [ ] URL: `data.median.firstView.final_url`
- [ ] browserName	`data.median.firstView.browser_name`
- [ ] browserVersion	`data.median.firstView.browserVersion`
- [ ] visualComplete85	`data.median.firstView.visualComplete85`
- [ ] visualComplete90	`data.median.firstView.visualComplete90`
- [ ] visualComplete95	`data.median.firstView.visualComplete95`
- [ ] breakdown.flash.bytes	`data.median.firstView.breakdown.flash.bytes`
- [ ] breakdown.flash.requests	`data.median.firstView.breakdown.flash.requests`
- [ ] breakdown.video.bytes	`data.median.firstView.breakdown.video.bytes`
- [ ] breakdown.video.requests	`data.median.firstView.breakdown.video.requests`
- [ ] bytesOut: The total bytes sent from the browser to other servers.
- [ ] bytesOutDoc: Same as bytesOut but only includes bytes until the Document Completeevent. Usually when all the page content has loaded (window.onload).
- [ ] bytesIn: The amount of data that browser had to download in order to load the page. Itis also commonly referred to as the page size.
- [ ] bytesInDoc: Same as bytestIn but only includes bytes until Document Completeevent.
- [ ] connections: The number of connections used.requests: List of details of all requests on tested page.
- [ ] requestsDoc: The number of requests until Document Complete event.
- [ ] responses_200: The number of responses with HTTP status code of 200, OK.
- [ ] responses_404: The number of responses with HTTP status code of 404, not　found.
- [ ] responses_other: The number of responses with HTTPS status code different from 200 or 404

**Comment by uknmr** [comment]
そうですね！自分がとりあえず見れればよかったものしか取ってなかったので取ったほうがいいですね😇
